### ISSUE TITLE
Please follow semver!

### ISSUE THREAD

**Issue by simonschaufi** [IndyIndyIndy/impersonate#8]
Whenever you drop a TYPO3 version, you have to release a new major release and not jumping from 2.0 to 2.1! That drives update bots crazy! Thank you!

**Comment by EvilBMP** [comment]
Please be more polite - it's not necessary to shout out "!" every sentence ;-) 

That tag was a bit historically, as I tried to release a version, that is compatible to TYPO3 v11 & v12, which at the end didn't work out. Unfortunately I missed to update the version to a new major - sorry about that. There is now a 3.0.0 available. Thanks for sending feedback and using the plugin.

**Comment by simonschaufi** [comment]
I'm sorry that I got a bit angry yesterday.
Thank you for this extension.
